//! Skills synthesis model.
//!
//! Skills live in a single content-addressed store at
//! `~/.aenv/store/objects/<sha>/`. Per-env activation generates a wrapper
//! plugin under `~/.aenv/envs/<env>/.claude/plugins/skill-<name>/` containing:
//!   - `plugin.json`  (so Claude Code recognizes it as a plugin)
//!   - `.aenv-managed` marker
//!   - `skills/<name>/` -> hardlink/symlink fanout to the store entry
//!
//! Why wrapper-plugin rather than copy: dedup. The same skill activated in
//! 5 envs costs disk once. Marker file lets `aenv doctor` distinguish
//! aenv-generated plugins from user-installed ones.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};

use crate::env::Env;
use crate::paths;
use crate::store;

pub const MANAGED_MARKER: &str = ".aenv-managed";

/// Detect whether a plugin directory was generated by aenv.
/// Used by `doctor` to flag managed wrappers separately from user plugins.
pub fn is_managed(plugin_dir: &Path) -> bool {
    plugin_dir.join(MANAGED_MARKER).is_file()
}

#[derive(Debug, Serialize, Deserialize)]
struct WrapperPluginJson {
    name: String,
    version: String,
    description: String,
}

/// Materialize a single skill into an env: ensure store has it, then create
/// a wrapper plugin pointing to it.
pub fn install_skill_into_env(env: &Env, skill_name: &str, sha256: &str) -> Result<PathBuf> {
    let plugins_root = env.claude_dir().join("plugins");
    paths::ensure_dir(&plugins_root)?;
    let wrapper = plugins_root.join(format!("skill-{skill_name}"));
    if wrapper.exists() {
        std::fs::remove_dir_all(&wrapper)?;
    }
    paths::ensure_dir(&wrapper)?;

    // 1. plugin.json
    let pj = WrapperPluginJson {
        name: format!("skill-{skill_name}"),
        version: "0.0.0".to_string(),
        description: format!("aenv-managed wrapper for skill '{skill_name}'"),
    };
    let pj_body = serde_json::to_string_pretty(&pj)?;
    std::fs::write(wrapper.join("plugin.json"), pj_body)?;

    // 2. marker
    std::fs::write(wrapper.join(MANAGED_MARKER), b"aenv-managed\n")?;

    // 3. skill content via hardlink fanout from store.
    let skill_dst = wrapper.join("skills").join(skill_name);
    paths::ensure_dir(skill_dst.parent().unwrap())?;
    store::materialize(sha256, &skill_dst)
        .with_context(|| format!("materialize skill '{skill_name}' from store"))?;
    Ok(wrapper)
}
